default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV.fetch('DATABASE_PASSWORD') { '' } %>
  host: <%= ENV.fetch('DATABASE_HOST') { 'localhost' } %>
  pool: <%= ENV.fetch('DATABASE_POOL') { 5 } %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>

development:
  <<: *default
  database: family-tasks-development

test:
  <<: *default
  database: family-tasks-test

production:
  <<: *default
  database: family-tasks-prod
